### PR TITLE
Support half precision for VQ and FSQ

### PR DESCRIPTION
**Pull request by JunityZhan**
Hi, I notice it is not support other preicsion. I made this tiny change and I tried a simple sample and it works on fp16 and bf16.
I noticed that there is a x = x.float(), I just comment it. I don't know if it is necessary. In my experiment, it just works fine, we can choose any precision into it.

### CODE REVIEW

**Comment by lucidrains** [comment]
@JunityZhan are you sure? researchers are telling me it doesn't perform well at all with low precision.

**Comment by JunityZhan** [comment]
> @JunityZhan are you sure? researchers are telling me it doesn't perform well at all with low precision.

In training, I think it is better to train it with fp32. However, in inference, I change it to fp16, and the precision of fp16 does not affect anything on quantized result. For e.g. you have 0.53244378278482 and 0.5324437 in fp32 and 16(just an example), you use FSQ, they will round to exactly the same number.

**Comment by JunityZhan** [comment]
btw, it fix #145

**Comment by lucidrains** [comment]
@JunityZhan ok, if what you are saying is true, then i can think about it

but your fix will break for your own condition `In training, I think it is better to train it with fp32.` correct?

**Comment by JunityZhan** [comment]
@lucidrains I am not sure I understand what you said about my fix will break for my own condition. If I dont make that change, I cannot inference it with fp16. The change is just to make sure we can choose whatever precision we like. No matter you want to train it with fp16, fp32, inference it with fp16, fp32, they are allowed. If I don't make that change, I cant inference it with fp16.
BTW, even in my test it is better to train it with fp32, it is still posible some tasks we can use fp16, bf16 or other precision, not to mention the need to inference it with fp16.

**Comment by lucidrains** [comment]
@JunityZhan right right. the difference is whether i always enforce f32 during training so that people (non researchers) have a greater chance of success using the library, or allow for flexibility. let me think about it

**Comment by lucidrains** [comment]
@JunityZhan do you want to see if setting [this](https://github.com/lucidrains/vector-quantize-pytorch/commit/be92f7908b938cf00c60d643c5ecffb01c7fa9fc#diff-3488501716ef0c4a1b84127592be7e1015e0faf0d7d3b630b69d88e55a134701R117) `False` works for you?

**Comment by JunityZhan** [comment]
> @JunityZhan do you want to see if setting [this](https://github.com/lucidrains/vector-quantize-pytorch/commit/be92f7908b938cf00c60d643c5ecffb01c7fa9fc#diff-3488501716ef0c4a1b84127592be7e1015e0faf0d7d3b630b69d88e55a134701R117) `False` works for you?

I think you only make modification on looks up quantization, but not vq and fsq

**Comment by lucidrains** [comment]
@JunityZhan that will come after LFQ works

**Comment by lucidrains** [comment]
@JunityZhan ahh yes, you wanted to do FSQ, let me apply that as well

**Comment by lucidrains** [comment]
@JunityZhan ok, try it now for [FSQ](https://github.com/lucidrains/vector-quantize-pytorch/commit/16ec0a84cb30e7854d7d7a0122e146a69e87f946#diff-9c80b206e8fc15897ee792a2c9a2ea0f76f39489f3bb67bb498592a58b03aab6R65) and if it works out, i'll do the same strat for vq

**Comment by lucidrains** [comment]
@JunityZhan ok, Marco reports it is working, closing

**Pull request closed without merging**
