### PR TITLE
Breaking change: compute and return code book usage

### PR DESCRIPTION
**Pull request by kashif**
adds and another argument to the output so a breaking change.

### CODE REVIEW

**Comment by lucidrains** [comment]
@kashif Hi Kashif and thanks for the PR!

I was wondering in what context do you need this perplexity and couldn't this be derived from the embedding indices (which is one of the return arguments)?

I just think perhaps not everyone would want this calculation done during training

**Comment by kashif** [comment]
right you are correct... I use it to debug how much the code book is being used ... let me see how to calculate it from the indices and I can close this then...

**Comment by kashif** [comment]
would you have an snippet to go from the `index` back to `embed_onehot` ?

**Comment by lucidrains** [comment]
@kashif one proxy for codebook usage is the cluster size https://github.com/lucidrains/vector-quantize-pytorch/blob/master/vector_quantize_pytorch/vector_quantize_pytorch.py#L211 the dead codebook revival logic in this repository actually relies on this

**Comment by lucidrains** [comment]
@kashif yup, you can just use the same logic within the repository https://github.com/lucidrains/vector-quantize-pytorch/blob/master/vector_quantize_pytorch/vector_quantize_pytorch.py#L279

**Comment by kashif** [comment]
ah yes! you are so right! I missed that thanks! Closing!

**Comment by pjyazdian** [comment]
I had the same issue with this library and defined the following function to calculate perplexity or average codebook usage based on my previous work [Gesture2Vece ](https://github.com/pjyazdian/Gesture2Vec). In the Gesture2Vec project, I also used soft-vector quantization which was very helpful. 


```
def Perplexity_Calculator(indices):
        # Method 1
        encoding_indices = indices.unsqueeze(1)
        encodings = F.one_hot(indices, codebook_size).type(indices.dtype)
        encodings = torch.Tensor.float(encodings).squeeze(1)
        avg_probs = torch.mean(encodings, dim=0)
        perplexity = torch.exp(-torch.sum(avg_probs * torch.log(avg_probs + 1e-10)))

        # Method 2
        encodings = torch.zeros(indices.shape[0], codebook_size, device=indices.device)
        encodings.scatter_(1, indices, 1)
        avg_probs = torch.mean(encodings.float(), dim=0)
        perplexity = torch.exp(-torch.sum(avg_probs * torch.log(avg_probs + 1e-10)))

        return perplexity
```

**Pull request closed without merging**
