### PR TITLE
Add note to maybe experiment with temperature

### PR DESCRIPTION
**Pull request by matwilso**
Feel free to reject if you think 100.0 is a better default, but for my own problem I found much better results for inv temperature of 10 or even 1.0

### CODE REVIEW

**Comment by lucidrains** [comment]
ah interesting

i'm guessing you are using LFQ for some reason for tesla autopilot?

**Comment by lucidrains** [comment]
so the author of the technique actually set it to 100, so i'm wary of changing it

your experience is worth something though, and maybe it can be put in the readme somewhere

**Comment by matwilso** [comment]
> ah interesting
> 
> i'm guessing you are using LFQ for some reason for tesla autopilot?

Haha potentially. Not at the moment, just kind of messing with it for now, studying some recent video generative models over the holidays that look interesting (magvit-v2 / videopoet)

**Comment by matwilso** [comment]
> so the author of the technique actually set it to 100, so i'm wary of changing it
> 
> your experience is worth something though, and maybe it can be put in the readme somewhere

Yeah fair enough, I can see about just adding a note so that people know to maybe mess with that parameter.

**Comment by lucidrains** [comment]
👍

**Pull request merged**
