### PR TITLE
Add a simple test suite

### PR DESCRIPTION
**Pull request by MisterBourbaki**
The proposition is simple: use the pytest plugin [pytest-examples](https://pypi.org/project/pytest-examples/) to efficiently test all examples writtent in the README. This enforces simple tests of the package, in particular thanks to the dedicated GitHub workflow.

- Add pytest and pytest-examples to the pyproject.toml ;
- Add both tests/test_examples_readme.py and .github/workflows/test.yml to automatically get all examples provided in the README and test them.
- Update the README itself to include print statements of the shape of various important tensors, instead of the comments.

There is no modification of the code itself! This PR is only for providing a first, simple test suite.

### CODE REVIEW

**Comment by MisterBourbaki** [comment]
Nota Bene: this is thanks to thoses tests that I uncovered the issue #123 😄

**Comment by lucidrains** [comment]
@MisterBourbaki i never knew about this! this is exactly how i wanted things

you read my mind; thank you

**Comment by MisterBourbaki** [comment]
You are very welcome :) 

I have a few other ideas to help improve the code... I will try to implement those, step by step ;) 
This is really a great project, thanks for your hard work!

**Comment by lucidrains** [comment]
@MisterBourbaki sounds good, i may push back on some, but 'pytest_examples' is really nice and will def start converting some other repos to this type of integration testing

**Comment by lucidrains** [comment]
@MisterBourbaki yea, Samuel is legendary!

ruff is fine with me!

**Comment by lucidrains** [comment]
hmm, `pytest-examples` seems kind of limited still

maybe i'll have to contribute a few more functionalities to it

**Comment by MisterBourbaki** [comment]
> hmm, `pytest-examples` seems kind of limited still
> 
> maybe i'll have to contribute a few more functionalities to it

For sure it is. It aims only at running and checking the examples in documentations.
Have you run into some issues with it? or are you thining about more tests, more complex?

**Pull request merged**
