### PR TITLE
changed eps

### PR DESCRIPTION
**Pull request by theAdamColton**
Hi, I was getting some NANs in the entropy loss term when training with fp16. I verified that this was fixed when increasing eps a little bit.

### CODE REVIEW

**Comment by lucidrains** [comment]
nice! thank you!

how is LFQ holding up in your experiments otherwise?

**Comment by theAdamColton** [comment]
lfq is great
I don't know if entropy loss makes a big difference. But even without any entropy loss, with properly normalized inputs, lfq gets really good perplexity/codebook usage. 
I haven't played around with whether commitment loss makes a difference. 

I'm using LFQ for transformers, to try and train an image autoencoder over DCT features [your-vae-sucks](https://theadamcolton.github.io/your-vae-sucks.html)

**Comment by lucidrains** [comment]
@theAdamColton great to hear you are seeing positive results! i haven't witnessed the improvements first hand but will get back into autoencoders soon

**Comment by lucidrains** [comment]
@theAdamColton LFQ is super interesting to me as the binary codes [are perfect for genetic algorithms](https://www.nature.com/articles/s41598-021-96812-8)

**Comment by lucidrains** [comment]
@theAdamColton if you ever hit a roadblock or a negative result, do let me know. it will save all of us a bunch of time and compute

**Comment by VJJJJJJ1** [comment]
> Hi, I was getting some NANs in the entropy loss term when training with fp16. I verified that this was fixed when increasing eps a little bit.
hi, I use the fixed eps which is 1e-5, but I still got nan in first 200 step. Is there any solution?

**Comment by VJJJJJJ1** [comment]
@lucidrains @theAdamColton

**Pull request merged**
